# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72528e00126710a7d6a61627a50a0710fbc7745d1425450e4b339d6b39dc0e7cb72eecba80e404bd7751722b71419d05da032aa785b524ca031745211f4e0a3a

test:
  secret_key_base: 8dd11726a5715c5d495e241ba7da3cde7c422ae69656e9dddbc3df2df1be2c8cf62b5937db4a2c4487a39e35c34d1ba3a88becf9141c74b342650d3270866081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
